apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardrailx-frontend
  labels:
    app: guardrailx-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guardrailx-frontend
  template:
    metadata:
      labels:
        app: guardrailx-frontend
    spec:
      containers:
        - name: frontend
          image: guardrailx-frontend:latest
          ports:
            - containerPort: 80
