apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-frontend
  labels:
    app: aegis-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aegis-frontend
  template:
    metadata:
      labels:
        app: aegis-frontend
    spec:
      containers:
        - name: frontend
          image: aegis-frontend:latest
          ports:
            - containerPort: 80
